apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-vault-sa
  namespace: {{ .Values.namespace }}
  annotations:
    vault.hashicorp.com/role: {{ .Values.global.vault.role | quote }}
